const DATAINVALID = 400;
const NOTFOUND = 404;
const SERVERERROR = 500;
const CONFLICTERROR = 409;
const AUTHENTICATIONERROR = 401;
const FORBIDDEN = 403;

module.exports = {
  DATAINVALID,
  NOTFOUND,
  SERVERERROR,
  CONFLICTERROR,
  AUTHENTICATIONERROR,
  FORBIDDEN,
};
